-- MySQL initialization script for autonomous trading bot database
-- Idempotent: uses IF NOT EXISTS and ON DUPLICATE KEY UPDATE where applicable

-- Create and use database (DB name should be created by startup.sh already)
-- This script assumes the database is already selected via -D or USE command in the caller.

-- Users table
CREATE TABLE IF NOT EXISTS users (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  email VARCHAR(255) NOT NULL UNIQUE,
  password_hash VARCHAR(255) NULL,
  display_name VARCHAR(100) NULL,
  is_active TINYINT(1) NOT NULL DEFAULT 1,
  is_admin TINYINT(1) NOT NULL DEFAULT 0,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  INDEX idx_users_is_active (is_active)
) ENGINE=InnoDB;

-- API keys per user, provider scoped
CREATE TABLE IF NOT EXISTS api_keys (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  user_id BIGINT UNSIGNED NOT NULL,
  provider ENUM('ZERODHA','NEWSAPI','OTHER') NOT NULL,
  api_key VARCHAR(512) NOT NULL,
  meta JSON NULL,
  is_active TINYINT(1) NOT NULL DEFAULT 1,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uniq_user_provider (user_id, provider),
  INDEX idx_api_keys_active (is_active),
  CONSTRAINT fk_api_keys_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB;

-- Bot configuration key-value (scoped optionally by user)
CREATE TABLE IF NOT EXISTS bot_config (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  user_id BIGINT UNSIGNED NULL,
  config_key VARCHAR(100) NOT NULL,
  config_value TEXT NULL,
  value_json JSON NULL,
  description VARCHAR(255) NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uniq_user_key (user_id, config_key),
  INDEX idx_config_key (config_key),
  CONSTRAINT fk_bot_config_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB;

-- Signals generated by strategy
CREATE TABLE IF NOT EXISTS signals (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  symbol VARCHAR(50) NOT NULL,
  signal_type ENUM('BUY','SELL') NOT NULL,
  confidence DECIMAL(6,4) NOT NULL DEFAULT 0.0000,
  source ENUM('STRATEGY','NEWS','ML','MANUAL') NOT NULL DEFAULT 'STRATEGY',
  reason TEXT NULL,
  metadata JSON NULL,
  status ENUM('PENDING','EXECUTED','CANCELLED','EXPIRED') NOT NULL DEFAULT 'PENDING',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  INDEX idx_signals_symbol_created (symbol, created_at),
  INDEX idx_signals_status (status)
) ENGINE=InnoDB;

-- Trades executed or simulated
CREATE TABLE IF NOT EXISTS trades (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  user_id BIGINT UNSIGNED NULL,
  signal_id BIGINT UNSIGNED NULL,
  broker_order_id VARCHAR(100) NULL,
  symbol VARCHAR(50) NOT NULL,
  side ENUM('BUY','SELL') NOT NULL,
  product ENUM('FUTURES','OPTIONS','EQUITY','CURRENCY') NOT NULL DEFAULT 'FUTURES',
  quantity INT NOT NULL,
  price DECIMAL(18,6) NOT NULL,
  status ENUM('PENDING','FILLED','PARTIAL','CANCELLED','REJECTED','CLOSED') NOT NULL DEFAULT 'PENDING',
  pnl DECIMAL(18,6) NULL,
  fees DECIMAL(18,6) NULL,
  entry_time TIMESTAMP NULL DEFAULT NULL,
  exit_time TIMESTAMP NULL DEFAULT NULL,
  notes TEXT NULL,
  metadata JSON NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  INDEX idx_trades_symbol_time (symbol, created_at),
  INDEX idx_trades_status (status),
  INDEX idx_trades_user (user_id),
  CONSTRAINT fk_trades_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL,
  CONSTRAINT fk_trades_signal FOREIGN KEY (signal_id) REFERENCES signals(id) ON DELETE SET NULL
) ENGINE=InnoDB;

-- News items and basic sentiment
CREATE TABLE IF NOT EXISTS news_items (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  source VARCHAR(100) NOT NULL,
  title VARCHAR(512) NOT NULL,
  url VARCHAR(1024) NOT NULL,
  published_at DATETIME NOT NULL,
  ticker VARCHAR(50) NULL,
  sentiment ENUM('POSITIVE','NEGATIVE','NEUTRAL','UNKNOWN') NOT NULL DEFAULT 'UNKNOWN',
  sentiment_score DECIMAL(6,4) NULL,
  content TEXT NULL,
  metadata JSON NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uniq_news_url (url),
  INDEX idx_news_published (published_at),
  INDEX idx_news_ticker (ticker),
  INDEX idx_news_sentiment (sentiment)
) ENGINE=InnoDB;

-- Logs/audit events
CREATE TABLE IF NOT EXISTS logs (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  level ENUM('DEBUG','INFO','WARN','ERROR') NOT NULL DEFAULT 'INFO',
  component VARCHAR(100) NOT NULL,
  message TEXT NOT NULL,
  context JSON NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  INDEX idx_logs_level (level),
  INDEX idx_logs_component_time (component, created_at)
) ENGINE=InnoDB;

-- Helpful composite indexes
CREATE INDEX IF NOT EXISTS idx_signals_symbol_status ON signals (symbol, status, created_at);
CREATE INDEX IF NOT EXISTS idx_trades_symbol_status ON trades (symbol, status, created_at);

-- Seed default admin/user and baseline config if not exists
INSERT INTO users (email, password_hash, display_name, is_active, is_admin)
SELECT 'admin@example.com', NULL, 'Admin', 1, 1
WHERE NOT EXISTS (SELECT 1 FROM users WHERE email = 'admin@example.com');

-- Seed default bot configuration
INSERT INTO bot_config (user_id, config_key, config_value, description)
SELECT NULL, 'risk.max_position_size', '100', 'Maximum quantity per position'
WHERE NOT EXISTS (SELECT 1 FROM bot_config WHERE user_id IS NULL AND config_key = 'risk.max_position_size');

INSERT INTO bot_config (user_id, config_key, config_value, description)
SELECT NULL, 'risk.max_daily_loss', '1000', 'Max loss allowed per day currency units'
WHERE NOT EXISTS (SELECT 1 FROM bot_config WHERE user_id IS NULL AND config_key = 'risk.max_daily_loss');

INSERT INTO bot_config (user_id, config_key, config_value, description)
SELECT NULL, 'trade.default_symbol', 'NIFTY', 'Default symbol for testing'
WHERE NOT EXISTS (SELECT 1 FROM bot_config WHERE user_id IS NULL AND config_key = 'trade.default_symbol');

-- Seed a welcome log line
INSERT INTO logs (level, component, message, context)
VALUES ('INFO', 'startup', 'Database initialized (startup.sql)', JSON_OBJECT('version', 'v1'));
